
import type { Watch } from '@/lib/types';

export const watchesData: Watch[] = [
  { 
    id: "WR001", 
    name: "Rolex Submariner Date", 
    brand: "Rolex", 
    price: 13500, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Rolex Submariner", 
    description: "Iconico orologio subacqueo, un classico intramontabile per ogni collezione.",
    rarity: 'Molto Richiesto',
    condition: 'Nuovo',
    isNewArrival: false,
    referenceNumber: "126610LN",
    caseMaterial: "Oystersteel",
    caseDiameter: "41mm",
    movementType: "Automatico",
    dialColor: "Nero",
    functions: ["Ora", "Minuti", "Secondi", "Data"],
  },
  { 
    id: "WO002", 
    name: "Omega Speedmaster Pro", 
    brand: "Omega", 
    price: 7200, 
    stock: 5, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Omega Speedmaster", 
    description: "Il leggendario \"Moonwatch\", un pezzo di storia al polso.",
    condition: 'Mint',
    isNewArrival: true,
    referenceNumber: "310.30.42.50.01.001",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "42mm",
    movementType: "Manuale",
    dialColor: "Nero",
    functions: ["Cronografo", "Tachimetro"],
  },
  { 
    id: "WPP003", 
    name: "Patek Philippe Nautilus", 
    brand: "Patek Philippe", 
    price: 150000, 
    stock: 1, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Patek Nautilus", 
    description: "Eleganza sportiva e design inconfondibile, un vero status symbol.",
    rarity: 'Ultra Raro',
    condition: 'Pre-owned Certificato',
    isNewArrival: false,
    referenceNumber: "5711/1A-010",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "40mm",
    movementType: "Automatico",
    dialColor: "Blu",
    functions: ["Ora", "Data"],
  },
  { 
    id: "WAP004", 
    name: "Audemars Piguet Royal Oak", 
    brand: "Audemars Piguet", 
    price: 55000, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Audemars RoyalOak", 
    description: "Design audace e finiture impeccabili per un orologio che non passa inosservato.",
    condition: 'Nuovo',
    isNewArrival: true,
    referenceNumber: "15500ST.OO.1220ST.03",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "41mm",
    movementType: "Automatico",
    dialColor: "Nero",
  },
  {
    id: 'WJC005',
    name: 'Jaeger-LeCoultre Reverso',
    brand: 'Jaeger-LeCoultre',
    price: 9800,
    stock: 3,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'JLC Reverso',
    description: 'Un classico Art Déco con cassa reversibile, esempio di eleganza e ingegnosità.',
    rarity: 'Iconico',
    condition: 'Nuovo',
    isNewArrival: false,
    referenceNumber: "Q3858522",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "45.6 x 27.4 mm",
    movementType: "Manuale",
    dialColor: "Argento",
  },
  {
    id: 'WCT006',
    name: 'Cartier Tank Louis Cartier',
    brand: 'Cartier',
    price: 12500,
    stock: 4,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'Cartier Tank',
    description: 'Design senza tempo che ha adornato i polsi di reali e celebrità per generazioni.',
    condition: 'Mint',
    isNewArrival: false,
    referenceNumber: "WGTA0011",
    caseMaterial: "Oro Giallo",
    caseDiameter: "33.7mm x 25.5mm",
    movementType: "Manuale",
    dialColor: "Argento",
  },
  { 
    id: "TEST001", 
    name: "OMEGA SEAMASTER - EDIZIONE TEST UNICA", 
    brand: "OMEGA (TEST)", 
    price: 99999, 
    stock: 1000, 
    imageUrl: "https://placehold.co/600x400/ff0000/ffffff.png?text=TEST+WATCH+VISIBLE", 
    dataAiHint: "test watch visible", 
    description: "OROLOGIO DI TEST UNICO E INCONFONDIBILE - Omega Seamaster Test Edition. Perfetta per collaudare le funzionalità dello shop. Robusta e affidabile.",
    rarity: 'UNICUM (Test)',
    condition: 'Nuovo di Fabbrica (Test)',
    isNewArrival: true, // Fondamentale per vederlo nei "Nuovi Arrivi"
    referenceNumber: "TEST-REF-001-VISIBLE",
    caseMaterial: "Adamantio di Test",
    caseDiameter: "42mm (Test)",
    movementType: "Automatico Co-Axial Potenziato (Test)",
    dialColor: "Rosso Fuoco (Test)",
    functions: ["Ora Esatta (Test)", "Data Cosmica (Test)", "Resistenza Estrema (Test)"],
    complications: ["Fasi Lunari Multiple (Test)", "Teletrasporto (Beta Test)"],
    yearOfProduction: new Date().getFullYear(), // Anno corrente per test
    additionalImageUrls: [
        "https://placehold.co/600x400/00ff00/000000.png?text=Test+Img+1+Green",
        "https://placehold.co/600x400/0000ff/ffffff.png?text=Test+Img+2+Blue"
    ]
  }
];
