
import type { Watch } from '@/lib/types';

export const watchesData: Watch[] = [
  { 
    id: "WR001", 
    name: "Rolex Submariner Date", 
    brand: "Rolex", 
    price: 13500, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Rolex Submariner", 
    description: "Iconico orologio subacqueo, un classico intramontabile per ogni collezione.",
    rarity: 'Molto Richiesto',
    condition: 'Nuovo',
    isNewArrival: false,
    referenceNumber: "126610LN",
    caseMaterial: "Oystersteel",
    caseDiameter: "41mm",
    movementType: "Automatico",
    dialColor: "Nero",
    functions: ["Ora", "Minuti", "Secondi", "Data"],
  },
  { 
    id: "WO002", 
    name: "Omega Speedmaster Pro", 
    brand: "Omega", 
    price: 7200, 
    stock: 5, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Omega Speedmaster", 
    description: "Il leggendario \"Moonwatch\", un pezzo di storia al polso.",
    condition: 'Mint',
    isNewArrival: true,
    referenceNumber: "310.30.42.50.01.001",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "42mm",
    movementType: "Manuale",
    dialColor: "Nero",
    functions: ["Cronografo", "Tachimetro"],
  },
  { 
    id: "WPP003", 
    name: "Patek Philippe Nautilus", 
    brand: "Patek Philippe", 
    price: 150000, 
    stock: 1, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Patek Nautilus", 
    description: "Eleganza sportiva e design inconfondibile, un vero status symbol.",
    rarity: 'Ultra Raro',
    condition: 'Pre-owned Certificato',
    isNewArrival: false,
    referenceNumber: "5711/1A-010",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "40mm",
    movementType: "Automatico",
    dialColor: "Blu",
    functions: ["Ora", "Data"],
  },
  { 
    id: "WAP004", 
    name: "Audemars Piguet Royal Oak", 
    brand: "Audemars Piguet", 
    price: 55000, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Audemars RoyalOak", 
    description: "Design audace e finiture impeccabili per un orologio che non passa inosservato.",
    condition: 'Nuovo',
    isNewArrival: true,
    referenceNumber: "15500ST.OO.1220ST.03",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "41mm",
    movementType: "Automatico",
    dialColor: "Nero",
  },
  {
    id: 'WJC005',
    name: 'Jaeger-LeCoultre Reverso',
    brand: 'Jaeger-LeCoultre',
    price: 9800,
    stock: 3,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'JLC Reverso',
    description: 'Un classico Art Déco con cassa reversibile, esempio di eleganza e ingegnosità.',
    rarity: 'Iconico',
    condition: 'Nuovo',
    isNewArrival: false,
    referenceNumber: "Q3858522",
    caseMaterial: "Acciaio Inox",
    caseDiameter: "45.6 x 27.4 mm",
    movementType: "Manuale",
    dialColor: "Argento",
  },
  {
    id: 'WCT006',
    name: 'Cartier Tank Louis Cartier',
    brand: 'Cartier',
    price: 12500,
    stock: 4,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'Cartier Tank',
    description: 'Design senza tempo che ha adornato i polsi di reali e celebrità per generazioni.',
    condition: 'Mint',
    isNewArrival: false,
    referenceNumber: "WGTA0011",
    caseMaterial: "Oro Giallo",
    caseDiameter: "33.7mm x 25.5mm",
    movementType: "Manuale",
    dialColor: "Argento",
  },
  { 
    id: "TEST001", 
    name: "Omega Seamaster Test Edition", 
    brand: "Omega", 
    price: 6500, 
    stock: 3, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Omega Seamaster test", 
    description: "Un'edizione speciale di test del Seamaster, perfetta per collaudare le funzionalità dello shop. Robusta e affidabile.",
    rarity: 'Test Sample',
    condition: 'Nuovo (Test)',
    isNewArrival: true,
    referenceNumber: "TEST-REF-001",
    caseMaterial: "Acciaio Inox di Test",
    caseDiameter: "42mm",
    movementType: "Automatico Co-Axial (Test)",
    dialColor: "Blu Test",
    functions: ["Ora di Test", "Data di Test", "Resistenza Test"],
    complications: ["Fasi Lunari di Test"],
    yearOfProduction: 2024,
    additionalImageUrls: [
        "https://placehold.co/600x400.png?text=Test+Img+1",
        "https://placehold.co/600x400.png?text=Test+Img+2"
    ]
  }
];

