
import type { Watch } from '@/lib/types';

export const watchesData: Watch[] = [
  { 
    id: "WR001", 
    name: "Rolex Submariner Date", 
    brand: "Rolex", 
    price: 13500, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Rolex Submariner", 
    description: "Iconico orologio subacqueo, un classico intramontabile per ogni collezione.",
    rarity: 'Molto Richiesto',
    condition: 'Nuovo',
  },
  { 
    id: "WO002", 
    name: "Omega Speedmaster Pro", 
    brand: "Omega", 
    price: 7200, 
    stock: 5, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Omega Speedmaster", 
    description: "Il leggendario \"Moonwatch\", un pezzo di storia al polso.",
    condition: 'Mint',
  },
  { 
    id: "WPP003", 
    name: "Patek Philippe Nautilus", 
    brand: "Patek Philippe", 
    price: 150000, 
    stock: 1, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Patek Nautilus", 
    description: "Eleganza sportiva e design inconfondibile, un vero status symbol.",
    rarity: 'Ultra Raro',
    condition: 'Pre-owned Certificato',
  },
  { 
    id: "WAP004", 
    name: "Audemars Piguet Royal Oak", 
    brand: "Audemars Piguet", 
    price: 55000, 
    stock: 2, 
    imageUrl: "https://placehold.co/600x400.png", 
    dataAiHint: "Audemars RoyalOak", 
    description: "Design audace e finiture impeccabili per un orologio che non passa inosservato.",
    condition: 'Nuovo',
  },
  {
    id: 'WJC005',
    name: 'Jaeger-LeCoultre Reverso',
    brand: 'Jaeger-LeCoultre',
    price: 9800,
    stock: 3,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'JLC Reverso',
    description: 'Un classico Art Déco con cassa reversibile, esempio di eleganza e ingegnosità.',
    rarity: 'Iconico',
    condition: 'Nuovo',
  },
  {
    id: 'WCT006',
    name: 'Cartier Tank Louis Cartier',
    brand: 'Cartier',
    price: 12500,
    stock: 4,
    imageUrl: 'https://placehold.co/600x400.png',
    dataAiHint: 'Cartier Tank',
    description: 'Design senza tempo che ha adornato i polsi di reali e celebrità per generazioni.',
    condition: 'Mint',
  },
];
